apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    project: booking-system-web
  labels:
    app: booking-system-web
  name: booking-system-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-system-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      annotations:
        project: booking-system-web
      labels:
        app: booking-system-web
    spec:
      containers:
      - image: kubelancer/booking-system:v3
        imagePullPolicy: ""
        name: booking-system-web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    project: booking-system-web
  labels:
    app: booking-system-web
  name: booking-system-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: booking-system-web
