apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    project: sample-web-app
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      annotations:
        project: sample-web-app
      labels:
        app: web
    spec:
      containers:
      - image: kubelancer/simple-web-app:v2
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    project: sample-web-app
  labels:
    app: web
  name: web-service
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: web
